# Analysis on TSP Benchmarking
 **Yuning Zhang @ SUSTech 2019.8**

In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
os.chdir("..")

In [9]:
qaoa_solution_file="./data/qaoa_tsp_solution_n=4_N=100_p=1_method=COBYLA"
classical_solution_file="./data/classical_tsp_solution_n=4_N=100"

In [12]:
qaoa_solution=pd.read_csv(qaoa_solution_file)
classical_solution=pd.read_csv(classical_solution_file)

In [14]:
qaoa_solution

,Unnamed: 0,opt_param,final_state,cost,mean_cost,n_iteration
0,0,[ 2.90019952 -0.00631379],"[0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0]",20.0,21.033580,13
1,1,[1.00000000e-01 2.85768455e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",26.0,26.023853,10
2,2,[1.00000000e-01 6.19705198e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",22.0,22.003396,10
3,3,[ 2.90019952 -0.00631379],"[0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0]",23.0,26.875926,13
4,4,[ 0.04812845 -0.02501752],[],13.0,13.750940,14
5,5,[1.00000000e-01 1.98824952e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",18.0,18.010214,10
6,6,[-1.00000000e-01 4.68567851e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",18.0,18.006806,10
7,7,[ 1.35 -0.30000002],"[0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]",20.0,22.781457,12
8,8,[2.91243875 0.04830142],"[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]",21.0,22.849852,13
9,9,[1.00000000e-01 1.29831368e-12],[],19.0,19.011918,10
10,10,[-1.00000000e-01 4.29426344e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",23.0,23.015334,10
11,11,[1.00000000e-01 3.07632429e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",21.0,21.008522,10
12,12,[1.00000000e-01 4.41808104e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",15.0,15.001707,10
13,13,[-1.00000000e-01 4.50379496e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",18.0,18.006804,10
14,14,[ 0.04812845 -0.02501752],[],17.0,17.750940,14
15,15,[1.00000000e-01 1.95366282e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",18.0,18.023815,10
16,16,[1.00000000e-01 1.72382257e-12],[],18.0,18.010205,10
17,17,[ 0.04812845 -0.02501752],"[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]",11.0,11.750940,14
18,18,[1.00000000e-01 3.23305933e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",20.0,20.010211,10
19,19,[3.1172905 0.08702746],"[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]",15.0,17.919374,13
20,20,[ 1.8 -0.3],"[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]",20.0,22.190591,12
21,21,[2.90124639 0.01573926],"[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]",22.0,24.084806,13
22,22,[1.00000000e-01 6.55297913e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",21.0,21.001701,10
23,23,[1.0000000e-01 1.1102036e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",8.0,8.003408,10
24,24,[ 2.90069962 -0.01180822],"[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]",19.0,20.801502,13
25,25,[3.14319377 0.15271542],"[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]",28.0,27.979030,13
26,26,[ 3.06473001 -0.07622353],"[0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0]",15.0,16.833227,13
27,27,[1.00000000e-01 5.39941548e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",22.0,22.003396,10
28,28,[ 2.99486115 -0.48924595],"[0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0]",22.0,23.000505,13
29,29,[3.72477581 0.82236674],"[0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]",13.0,18.810029,14
...,...,...,...,...,...,...
70,70,[1.00000000e-01 8.98214544e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",28.0,28.003399,10
71,71,[ 2.91245949 -0.04833901],"[0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1]",10.0,12.217707,13
72,72,[1.00000000e-01 1.95881609e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",17.0,17.011906,10
73,73,[1.00000000e-01 6.99608222e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",27.0,27.005097,10
74,74,[ 3.13942621 -0.89443383],"[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]",21.0,20.959260,13
75,75,[ 2.90019952 -0.00631379],"[0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0]",12.0,12.516790,13
76,76,[1.00000000e-01 3.82454699e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",20.0,20.003413,10
77,77,[1.00000000e-01 4.89472979e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",20.0,20.003408,10
78,78,[ 3.13942621 -0.89443383],"[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]",27.0,26.959260,13
79,79,[ 3.05119922 -0.08589901],"[0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0]",15.0,15.879571,13
80,80,[ 2.90019952 -0.00631379],"[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]",19.0,22.359136,13
81,81,[ 1.8 -0.3],"[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]",16.0,18.190591,12
82,82,[1.00000000e-01 2.83578026e-12],"[1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1]",16.0,17.005114,10
83,83,[1.00000000e-01 3.35164839e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",21.0,21.008522,10
84,84,[1.00000000e-01 5.71796971e-12],[],21.0,21.005103,10
85,85,[ 3.28397928 -0.30343979],"[1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1]",18.0,19.035641,14
86,86,[ 3.06418345 -0.07668432],"[1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1]",16.0,18.623511,13
87,87,[-1.00000000e-01 1.80912326e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",10.0,10.003399,10
88,88,[1.00000000e-01 3.92051863e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",23.0,23.008525,10
89,89,[2.90001391e+00 1.66766537e-03],"[1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0]",21.0,22.799461,13
90,90,[3.28497943 0.43078019],"[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]",20.0,21.777184,14
91,91,[ 3.20000608 -0.88197512],"[0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0]",15.0,18.979857,13
92,92,[ 2.90019952 -0.00631379],"[0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0]",25.0,25.258395,13
93,93,[1.00000000e-01 7.49728852e-13],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",14.0,14.010220,10
94,94,[ 0.04794497 -0.02502112],[],13.0,14.753000,14
95,95,[ 1.8 -0.3],"[0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]",16.0,16.730197,12
96,96,[1.00000000e-01 1.61096052e-12],[],14.0,14.017035,10
97,97,[1.00000000e-01 5.92456178e-12],"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]",17.0,17.001701,10
98,98,[2.90410811 0.02836803],"[0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0]",18.0,20.039591,13
99,99,[2.90410811 0.02836802],"[0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]",21.0,22.019795,13